-- Script generated by Redgate Compare v1.22.1.23470
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.replays.fulllog...';END$$;
ALTER TABLE public.replays ADD COLUMN fulllog text;

SET check_function_bodies = true;
