-- Script generated by Redgate Compare v1.15.0.10313
SET check_function_bodies = false;

DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.games.id...';END$$;
ALTER TABLE public.games ALTER COLUMN id DROP DEFAULT, ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.games_id_seq...';END$$;
DROP SEQUENCE public.games_id_seq;

SET check_function_bodies = true;
