-- Script generated by Redgate Compare v1.15.0.10313
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.replays...';END$$;
CREATE TABLE public.replays (
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    status text,
    name text,
    tempfilename text
);
ALTER TABLE public.replays ADD CONSTRAINT replays_pk PRIMARY KEY (id);

SET check_function_bodies = true;
