# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes 🔨
      labels:
        - breaking change
    - title: New Features 🎉
      labels:
        - new feature
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"