id = "a7bc3a93-22da-49dc-8985-cebbe1add3bd"
name = "worms"
databaseType = "PostgreSql"

[environments.build]
url = "jdbc:postgresql://postgres:5432/worms"
user = "worms"
password = "worms"
provisioner = "clean"
cleanDisabled = "false"

[environments.development]
url = "jdbc:postgresql://localhost:5432/worms"
user = "worms"
password = "worms"
schemas = [ "public" ]
displayName = "Development database"
provisioner = "docker"

[environments.development.resolvers.docker]
waitTimeout = "1h"
composeFile = "C:\\code\\WormsLeague\\docker-compose.yaml"
services = [ "flyway-init" ]

[environments.shadow]
url = "jdbc:postgresql://localhost:5432/worms-shadow"
user = "worms"
password = "worms"
schemas = [ "public" ]
displayName = "Shadow database"
provisioner = "docker"

[environments.shadow.resolvers.docker]
waitTimeout = "1h"
composeFile = "C:\\code\\WormsLeague\\docker-compose.yaml"
services = [ "flyway-init" ]

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
validateMigrationNaming = true
publishResult = true

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "./schema-model"

[redgateCompare]
filterFile = "filter.rgf"
