using System.Diagnostics;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using NUnit.Framework;
using Shouldly;
using Worms.Hub.Queues;

namespace Worms.Hub.Armageddon.Runner.Tests;

// Prerequisite: WA game files must be at /home/eadie/games/worms and sample.WAGame must be in sample-data/replays/
// Run with: dotnet test --filter Category=Integration
// The test builds the Docker image and starts/stops services automatically.
[TestFixture]
[Category("Integration")]
internal sealed class ProcessReplayShould
{
    private const string ReplayFileName = "sample.WAGame";

    private const string AzuriteConnectionString =
        "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;"
        + "AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;"
        + "BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
        + "QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;";

    private string _repoRoot = null!;
    private string _replayFolder = null!;
    private IMessageQueue<ReplayToProcessMessage> _inputQueue = null!;
    private IMessageQueue<ReplayToUpdateMessage> _outputQueue = null!;

    [OneTimeSetUp]
    public async Task StartServices()
    {
        _repoRoot = FindRepoRoot();
        _replayFolder = Path.Combine(_repoRoot, "sample-data", "replays");

        await TestContext.Progress.WriteLineAsync("Building hub-wa-runner image...");
        await RunDockerCompose(_repoRoot, "build hub-wa-runner");
        await TestContext.Progress.WriteLineAsync("Starting services...");
        await RunDockerCompose(_repoRoot, "up -d azure-storage hub-wa-runner");
        await TestContext.Progress.WriteLineAsync("Waiting for Azurite...");
        await WaitForAzurite();
        await TestContext.Progress.WriteLineAsync("Services ready.");

        var services = new ServiceCollection()
            .AddSingleton<IConfiguration>(
                new ConfigurationBuilder()
                    .AddInMemoryCollection(
                        new Dictionary<string, string?> { ["ConnectionStrings:Storage"] = AzuriteConnectionString })
                    .Build())
            .AddQueueServices()
            .BuildServiceProvider();

        _inputQueue = services.GetRequiredService<IMessageQueue<ReplayToProcessMessage>>();
        _outputQueue = services.GetRequiredService<IMessageQueue<ReplayToUpdateMessage>>();
    }

    [SetUp]
    public void CleanUpLogFile()
    {
        var logFile = Path.Combine(_replayFolder, Path.GetFileNameWithoutExtension(ReplayFileName) + ".log");
        if (File.Exists(logFile))
        {
            File.Delete(logFile);
        }
    }

    [TearDown]
    public void CleanUpLogFileAfter() => CleanUpLogFile();

    [OneTimeTearDown]
    public async Task StopServices()
    {
        await RunDockerCompose(_repoRoot, "stop hub-wa-runner azure-storage");
    }

    [Test]
    public async Task ProduceALogFileFromAReplay()
    {
        var logFilePath = Path.Combine(_replayFolder, Path.GetFileNameWithoutExtension(ReplayFileName) + ".log");

        File.Exists(logFilePath).ShouldBeFalse("Log file should not exist before the test starts");

        await TestContext.Progress.WriteLineAsync($"Sending message for {ReplayFileName}...");
        await _inputQueue.EnqueueMessage(new ReplayToProcessMessage(ReplayFileName));

        await TestContext.Progress.WriteLineAsync("Waiting for log file (up to 2 minutes)...");
        await PollUntil(() => File.Exists(logFilePath), TimeSpan.FromMinutes(2));
        await TestContext.Progress.WriteLineAsync("Log file found.");

        File.Exists(logFilePath).ShouldBeTrue("Expected log file to be generated by the WA runner");
        new FileInfo(logFilePath).Length.ShouldBeGreaterThan(0, "Expected log file to contain content");

        await TestContext.Progress.WriteLineAsync("Waiting for output queue message...");
        await PollUntil(async () => await _outputQueue.HasPendingMessage(), TimeSpan.FromSeconds(10));

        var (outputMessage, _, _) = await _outputQueue.DequeueMessage();
        outputMessage.ShouldNotBeNull();
        outputMessage.ReplayFileName.ShouldBe(ReplayFileName);
    }

    private static string FindRepoRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "docker-compose.yaml")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("Could not find repo root (docker-compose.yaml not found)");
    }

    private static async Task RunDockerCompose(string workingDirectory, string arguments)
    {
        using var process = Process.Start(
            new ProcessStartInfo("docker", $"compose {arguments}")
            {
                WorkingDirectory = workingDirectory
            })!;
        await process.WaitForExitAsync();
    }

    private static readonly HttpClient _httpClient = new() { Timeout = TimeSpan.FromSeconds(2) };

    private static async Task WaitForAzurite()
    {
        var azuriteUri = new Uri("http://127.0.0.1:10001/devstoreaccount1");
        var deadline = DateTime.UtcNow.Add(TimeSpan.FromSeconds(30));
        while (DateTime.UtcNow < deadline)
        {
            try
            {
                _ = await _httpClient.GetAsync(azuriteUri);
                return;
            }
            catch (HttpRequestException)
            {
                await Task.Delay(TimeSpan.FromSeconds(1));
            }
            catch (TaskCanceledException)
            {
                await Task.Delay(TimeSpan.FromSeconds(1));
            }
        }

        throw new TimeoutException("Azurite did not become reachable within 30 seconds");
    }

    private static async Task PollUntil(Func<bool> condition, TimeSpan timeout)
    {
        var deadline = DateTime.UtcNow.Add(timeout);
        while (DateTime.UtcNow < deadline)
        {
            if (condition())
            {
                return;
            }

            await Task.Delay(TimeSpan.FromSeconds(2));
        }

        throw new TimeoutException($"Condition not met within {timeout.TotalSeconds}s timeout");
    }

    private static async Task PollUntil(Func<Task<bool>> condition, TimeSpan timeout)
    {
        var deadline = DateTime.UtcNow.Add(timeout);
        while (DateTime.UtcNow < deadline)
        {
            if (await condition())
            {
                return;
            }

            await Task.Delay(TimeSpan.FromSeconds(2));
        }

        throw new TimeoutException($"Condition not met within {timeout.TotalSeconds}s timeout");
    }
}
