name: ZZ - Build - CLI

on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run tests
        run: make cli.test.unit

  package-cli-windows:
    name: Package - Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: make cli.package.windows
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: .artifacts/win-x64/

  package-cli-linux-x64:
    name: Package - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: make cli.package.linux
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: .artifacts/linux-x64/

  package-cli-docker:
    name: Package - Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: make cli.package.docker
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: linux-musl-x64
          path: .artifacts/linux-musl-x64/
