name: CLI

on:
  push:
    paths:
      - "src/cli/**"
      - "build/**"
      - ".github/workflows/cli.yml"

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Run tests
        run: cd src/cli; dotnet test

  build-cli-windows:
    name: Build - Windows
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: cd src/cli; make windows
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: src/cli/.artifacts/win-x64/

  build-cli-linux-x64:
    name: Build - Linux
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: cd src/cli; make linux
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: src/cli/.artifacts/linux-x64/

  build-cli-linux-musl-x64:
    name: Build - Alpine
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: cd src/cli; make alpine
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: linux-musl-x64
          path: src/cli/.artifacts/linux-musl-x64/

  build-cli-docker:
    name: Build - Docker
    needs: build-cli-linux-musl-x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: linux-musl-x64
          path: src/cli/.artifacts/linux-musl-x64/
      - name: Build
        run: cd src/cli; make docker-build

  release-cli-github:
    name: Release - GitHub
    needs: build-cli-windows
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: win-x64
          path: src/cli/.artifacts/win-x64/
      - name: Release
        run: cd src/cli; make release-github GitHubAuthToken=${{ secrets.GITHUB_TOKEN }} GitHubRepo=${{ github.repository }}

  release-cli-dockerhub:
    name: Release - DockerHub
    needs: build-cli-docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: linux-musl-x64
          path: src/cli/.artifacts/linux-musl-x64/
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: theeadie
          password: ${{ secrets.DockerHubAccessToken }}
      - name: Release
        run: cd src/cli; make release-dockerhub
