name: CLI

on:
  push:
    paths:
      - "src/Directory.Build.props"
      - "src/Worms.Cli/**"
      - "src/Worms.Cli.*/**"
      - "src/Worms.Armageddon.*/**"
      - "build/cli/**"
      - "build/release-github.sh"
      - "build/version.sh"
      - ".github/workflows/cli.yml"

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run tests
        run: make cli.test.unit

  package-cli-windows:
    name: Package - Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: make cli.package.windows
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: .artifacts/win-x64/

  package-cli-linux-x64:
    name: Package - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: make cli.package.linux
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: .artifacts/linux-x64/

  package-cli-docker:
    name: Package - Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: make cli.package.docker
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: linux-musl-x64
          path: .artifacts/linux-musl-x64/

  overall-build:
    name: Overall Build
    needs:
      - unit-tests
      - package-cli-windows
      - package-cli-linux-x64
      - package-cli-docker
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Checked"

  release-cli-github:
    name: Release - GitHub
    needs: overall-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: win-x64
          path: .artifacts/win-x64/
      - name: Release
        run: make cli.release.github GitHubAuthToken=${{ secrets.GITHUB_TOKEN }} GitHubRepo=${{ github.repository }}

  release-cli-wormshub:
    name: Release - Worms Hub
    needs: overall-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download build - win-x64
        uses: actions/download-artifact@v4
        with:
          name: win-x64
          path: .artifacts/win-x64/
      - name: Download build - linux-x64
        uses: actions/download-artifact@v4
        with:
          name: linux-x64
          path: .artifacts/linux-x64/
      - name: Release
        run: make cli.release.wormshub WormsHubClientId=${{ secrets.WORMSHUB_CLIENTID }} WormsHubClientSecret=${{ secrets.WORMSHUB_CLIENTSECRET }}

  release-cli-dockerhub:
    name: Release - DockerHub
    needs: overall-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: linux-musl-x64
          path: .artifacts/linux-musl-x64/
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: theeadie
          password: ${{ secrets.DockerHubAccessToken }}
      - name: Release
        run: make cli.release.dockerhub
