name: Code - Branches
permissions:
  contents: write
  pull-requests: write
  security-events: write

on:
  push:
    branches-ignore:
      - "main"
    paths:
      - "src/**"
      - "build/**"
      - ".github/workflows/code-*.yml"
      - ".github/workflows/zz-build-*.yml"
      - ".github/workflows/zz-release-*.yml"
      - ".github/workflows/zz-detect-changes.yml"
      - ".github/workflows/zz-inspections.yml"

jobs:
  changes:
    name: Detect Changes
    uses: ./.github/workflows/zz-detect-changes.yml

  build-hub:
    name: Build - Hub
    needs: changes
    uses: ./.github/workflows/zz-build-hub.yml
    with:
      wa-runner-test: ${{ needs.changes.outputs.wa-runner-test }}
    secrets: inherit

  build-cli:
    name: Build - CLI
    needs: changes
    uses: ./.github/workflows/zz-build-cli.yml
    secrets: inherit

  actions-timeline:
    name: Timeline
    needs: [changes, build-hub, build-cli]
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v3
        with:
          show-waiting-runner: true
