name: Code - Branches
permissions:
  contents: write
  pull-requests: write
  security-events: write

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches: ["main"]

jobs:
  changes:
    name: Detect Changes
    uses: ./.github/workflows/zz-detect-changes.yml

  build-hub:
    name: Build - Hub
    needs: changes
    if: needs.changes.outputs.code == 'true'
    uses: ./.github/workflows/zz-build-hub.yml
    with:
      wa-runner-test: ${{ needs.changes.outputs.wa-runner-test }}
    secrets: inherit

  build-cli:
    name: Build - CLI
    needs: changes
    if: needs.changes.outputs.code == 'true'
    uses: ./.github/workflows/zz-build-cli.yml
    secrets: inherit

  build-web:
    name: Build - Web
    needs: changes
    if: needs.changes.outputs.code == 'true'
    uses: ./.github/workflows/zz-build-web.yml
    secrets: inherit

  deploy-preview:
    name: Deploy Preview
    needs: changes
    if: github.event_name == 'pull_request' && needs.changes.outputs.deployment == 'true'
    uses: ./.github/workflows/zz-deploy-preview.yml
    secrets: inherit

  overall-build:
    name: Overall Build
    if: always()
    needs: [changes, build-hub, build-cli, build-web, deploy-preview]
    runs-on: ubuntu-latest
    steps:
      - name: Check all builds passed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "::error::One or more build jobs failed"
            exit 1
          fi
      - uses: Kesin11/actions-timeline@v3
        if: always()
        with:
          show-waiting-runner: true
