name: Deploy - Preview

on:
  pull_request:
    paths:
      - "deployment/worms.davideadie.dev/**"
      - "build/flyway-summary.sh"
      - ".github/workflows/deploy.yml"

jobs:
  preview-azure:
    name: Azure
    runs-on: ubuntu-latest
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: prod
          work-dir: deployment/worms.davideadie.dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  preview-database:
    name: Database
    runs-on: ubuntu-latest
    env:
      FLYWAY_LICENSE_KEY: ${{ secrets.FLYWAY_LICENSE_KEY }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: worms
          POSTGRES_PASSWORD: worms
          POSTGRES_DB: worms
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: vars
        run: echo "version=$(cat deployment/worms.davideadie.dev/database-version.txt)" >> $GITHUB_OUTPUT

      - name: Run Flyway Report
        uses: docker://redgate/flyway:9
        with:
          args: >-
            -locations="filesystem:/github/workspace/src/database/migrations"
            -configFiles="/github/workspace/src/database/flyway.conf"
            -url="jdbc:postgresql://${{ secrets.PROD_DATABASE_HOST }}:${{ secrets.PROD_DATABASE_PORT }}/${{ secrets.PROD_DATABASE_NAME }}"
            -user="${{ secrets.PROD_DATABASE_USER }}"
            -password="${{ secrets.PROD_DATABASE_PASSWORD }}""
            check -changes -drift
            -check.buildUrl="jdbc:postgresql://postgres:5432/worms"
            -check.buildUser="worms"
            -check.buildPassword="worms"
            -target=${{ steps.vars.outputs.version }}
            -check.reportFilename="/flyway/reports/report.htm"

      - name: Get summary
        id: summary
        run: echo "summary=$(build/flyway-summary.sh src/database/reports/report.htm.json)" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.summary.outputs.summary }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: Database Report
          path: src/database/reports/
