name: Deploy

on:
  push:
    paths:
      - "deployment/worms.davideadie.dev/**"
      - ".github/workflows/deploy.yml"
    branches:
      - master

jobs:
  deploy-azure:
    name: Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Pulumi up
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: prod
          work-dir: deployment/worms.davideadie.dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  deploy-database:
    name: Database
    needs: deploy-azure
    runs-on: ubuntu-latest
    env:
      FLYWAY_LICENSE_KEY: ${{ secrets.FLYWAY_LICENSE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: vars
        run: echo "version=$(cat deployment/worms.davideadie.dev/database-version.txt)" >> $GITHUB_OUTPUT

      - name: Run Flyway Report
        uses: docker://redgate/flyway:9
        with:
          args: >-
            info
            migrate
            info
            -locations="filesystem:/github/workspace/src/database/migrations"
            -configFiles="/github/workspace/src/database/flyway.conf"
            -url="jdbc:postgresql://${{ secrets.PROD_DATABASE_HOST }}:${{ secrets.PROD_DATABASE_PORT }}/${{ secrets.PROD_DATABASE_NAME }}"
            -user="${{ secrets.PROD_DATABASE_USER }}"
            -password="${{ secrets.PROD_DATABASE_PASSWORD }}"
            -target=${{ steps.vars.outputs.version }}
