name: Deploy - PRs

on:
  pull_request:
    paths:
      - "deployment/Worms.Hub.Infrastructure/**"
      - "build/flyway-summary.sh"
      - ".github/workflows/deploy-pr.yml"

jobs:
  preview:
    name: Azure Infrastructure
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: worms
          POSTGRES_PASSWORD: worms
          POSTGRES_DB: worms
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Preview Azure Infrastructure
        uses: pulumi/actions@v6
        id: preview
        with:
          command: preview
          stack-name: prod
          work-dir: deployment/Worms.Hub.Infrastructure
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Create Reports Folder
        run: mkdir src/database/reports

      - name: Run Flyway Report
        uses: docker://redgate/flyway:10
        with:
          args: >-
            check -changes -drift
            -workingDirectory=/github/workspace/src/database
            -check.buildEnvironment=build
            -environment=production
            -url="${{ steps.preview.outputs.database-jdbc }}"
            -user="${{ steps.preview.outputs.database-user }}"
            -password="${{ steps.preview.outputs.database-password }}"
            -target=${{ steps.preview.outputs.database-version }}
            -reportFilename="/github/workspace/src/database/reports/report.htm"
        env:
          FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
          FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}

      - name: Get Summary
        id: summary
        run: echo "summary=$(build/flyway-summary.sh src/database/reports/report.json)" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ${{ steps.summary.outputs.summary }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: Database Report
          path: src/database/reports/
