name: Deploy

on:
  push:
    paths:
      - "deployment/Worms.Hub.Infrastructure/**"
      - ".github/workflows/deploy.yml"
    branches:
      - main

jobs:
  deploy:
    name: Azure Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Pulumi Up
        id: pulumi-up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: prod
          work-dir: deployment/Worms.Hub.Infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run Flyway Migrate
        uses: docker://redgate/flyway:10
        with:
          args: >-
            info
            migrate
            info
            -workingDirectory=/github/workspace/src/database
            -environment=production
            -url="${{ steps.pulumi-up.outputs.database-jdbc }}"
            -user="${{ steps.pulumi-up.outputs.database-user }}"
            -password="${{ steps.pulumi-up.outputs.database-password }}"
            -target=${{ steps.pulumi-up.outputs.database-version }}
        env:
          FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
          FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}

