name: Deploy - worms.davideadie.dev

on:
  push:
    paths:
    - "deployment/worms.davideadie.dev/**"
    - ".github/workflows/deploy.yml"

jobs:

  deploy-database:
    name: Deploy Database
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Flyway Migrate
      run: >-
        docker run --rm \
          --volume ${{ github.workspace }}/src/database/migrations:/flyway/sql:ro \
          flyway/flyway:8.5.9-alpine \
          -url="${{ secrets.PROD_DATABASE_URL }}" \
          -user="${{ secrets.PROD_DATABASE_USER }}" \
          -password="${{ secrets.PROD_DATABASE_PASSWORD }}" \
          migrate \
          -target=$(cat deployment/worms.davideadie.dev/database-version.txt)