name: Build Gif Tool

on:
  push:
    paths:
    - "src/giftool/**"
    - ".github/workflows/gif-tool.yml"

jobs:
  build-gif-tool:
    name: Build GIF tool
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: cd src/giftool; ./.build/build.ps1
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: GifTool
        path: src/giftool/.artifacts/

  release:
    name: Create GitHub Release for gif tool
    needs: build-gif-tool
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download Gif Tool
      uses: actions/download-artifact@v3
      with:
        name: GifTool
        path: src/giftool/.artifacts
    - name: Release
      run: ./src/giftool/.build/release.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} src/giftool/.artifacts
