name: Hub - Main

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/hub-build.yml
    secrets: inherit

  release:
    name: Release
    needs: build
    uses: ./.github/workflows/hub-release.yml
    secrets: inherit
