name: ZZ - Build - Web
permissions:
  contents: read

on:
  workflow_call:

jobs:
  test-web:
    name: Web UI - Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install dependencies
        run: cd src/Worms.Hub.Web && npm ci
      - name: Test
        run: make web.test

  package-web:
    name: Web UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Package
        run: make web.build
      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: web
          path: .artifacts/web/
