name: ZZ - Detect Changes
permissions:
  contents: read
  pull-requests: read

on:
  workflow_call:
    outputs:
      gateway-release:
        value: ${{ jobs.changes.outputs.gateway-release }}
      wa-runner-release:
        value: ${{ jobs.changes.outputs.wa-runner-release }}
      wa-runner-test:
        value: ${{ jobs.changes.outputs.wa-runner-test }}
      clis-release:
        value: ${{ jobs.changes.outputs.clis-release }}
      web-build:
        value: ${{ jobs.changes.outputs.web-build }}
      deployment:
        value: ${{ jobs.changes.outputs.deployment }}
      code:
        value: ${{ jobs.changes.outputs.code }}

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      gateway-release: ${{ steps.filter.outputs.gateway == 'true' || steps.filter.outputs.hub-common == 'true' }}
      wa-runner-release: ${{ steps.filter.outputs.wa-runner == 'true' || steps.filter.outputs.hub-common == 'true' }}
      wa-runner-test: ${{ steps.filter.outputs.wa-runner == 'true' || steps.filter.outputs.wa-runner-test == 'true' || steps.filter.outputs.hub-common == 'true' }}
      clis-release: ${{ steps.filter.outputs.clis == 'true' }}
      web-build: ${{ steps.filter.outputs.web == 'true' }}
      deployment: ${{ steps.filter.outputs.deployment == 'true' }}
      code: ${{ steps.filter.outputs.code == 'true' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Filter
      uses: dorny/paths-filter@v4
      id: filter
      with:
        filters: |
          gateway:
            - 'src/Worms.Armageddon.Files/**'
            - 'src/Worms.Hub.Gateway/**'
            - 'src/Worms.Hub.Queues/**'
            - 'src/Worms.Hub.Storage/**'
            - 'src/Worms.Hub.Web/**'
            - 'build/docker/gateway/**'
            - 'build/web/**'
          wa-runner:
            - 'src/Worms.Hub.Armageddon.Runner/**'
            - 'src/Worms.Armageddon.Files/**'
            - 'src/Worms.Armageddon.Game/**'
            - 'src/Worms.Armageddon.Gifs/**'
            - 'src/Worms.Hub.Queues/**'
            - 'build/docker/wa-runner/**'
          wa-runner-test:
            - 'src/Worms.Hub.Armageddon.Runner.Tests/**'
            - 'build/download-wa-game.sh'
          hub-common:
            - 'src/Directory.Build.props'
            - '.github/workflows/hub-*.yml'
            - 'build/docker/makefile'
            - 'build/*.sh'
          clis:
            - 'src/Worms.Cli/**'
            - 'src/Worms.Cli.*/**'
            - '!src/Worms.Cli.Tests/**'
            - 'src/Worms.Armageddon.Files/**'
            - 'src/Worms.Armageddon.Game/**'
            - 'src/Worms.Armageddon.Gifs/**'
            - 'src/Directory.Build.props'
            - 'build/cli/**'
            - '.github/workflows/hub-*.yml'
          web:
            - 'src/Worms.Hub.Web/**'
            - 'build/web/**'
          deployment:
            - 'deployment/Worms.Hub.Infrastructure/**'
            - 'build/flyway-summary.sh'
          code:
            - 'src/**'
            - 'build/**'
            - '.github/workflows/code-*.yml'
            - '.github/workflows/zz-build-*.yml'
            - '.github/workflows/zz-release-*.yml'
            - '.github/workflows/zz-detect-changes.yml'
            - '.github/workflows/zz-inspections.yml'
