name: ZZ - Release - CLI
permissions:
  contents: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      clis-changed:
        type: string
        required: true

jobs:

  release-cli-github:
    name: Release - GitHub
    runs-on: ubuntu-latest
    if: ${{ inputs.clis-changed == 'true' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: win-x64
          path: .artifacts/win-x64/
      - name: Release
        run: make cli.release.github GitHubAuthToken=${{ secrets.GITHUB_TOKEN }} GitHubRepo=${{ github.repository }}

  release-cli-wormshub:
    name: Release - Worms Hub
    runs-on: ubuntu-latest
    if: ${{ inputs.clis-changed == 'true' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download build - win-x64
        uses: actions/download-artifact@v8
        with:
          name: win-x64
          path: .artifacts/win-x64/
      - name: Download build - linux-x64
        uses: actions/download-artifact@v8
        with:
          name: linux-x64
          path: .artifacts/linux-x64/
      - name: Release
        run: make cli.release.wormshub WormsHubClientId=${{ secrets.WORMSHUB_CLIENTID }} WormsHubClientSecret=${{ secrets.WORMSHUB_CLIENTSECRET }}

  release-cli-dockerhub:
    name: Release - DockerHub
    runs-on: ubuntu-latest
    if: ${{ inputs.clis-changed == 'true' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: linux-musl-x64
          path: .artifacts/linux-musl-x64/
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: theeadie
          password: ${{ secrets.DockerHubAccessToken }}
      - name: Release
        run: make cli.release.dockerhub
