name: ZZ - Release - Hub
permissions:
  contents: write
  pull-requests: write

on:
  workflow_call:

jobs:

  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      gateway: ${{ steps.filter.outputs.gateway == 'true' || steps.filter.outputs.common == 'true' }}
      wa-runner: ${{ steps.filter.outputs.wa-runner == 'true' || steps.filter.outputs.common == 'true' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Filter
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          gateway:
            - 'src/Worms.Armageddon.Files/**'
            - 'src/Worms.Hub.Gateway/**'
            - 'src/Worms.Hub.Queues/**'
            - 'src/Worms.Hub.Storage/**'
            - 'build/docker/gateway/**'
          wa-runner:
            - 'src/Worms.Hub.Armageddon.Runner/**'
            - 'src/Worms.Armageddon.Game/**'
            - 'src/Worms.Hub.Queues/**'
            - 'build/docker/wa-runner/**'
          common:
            - 'src/Directory.Build.props'
            - '.github/workflows/hub-*.yml'
            - 'build/docker/makefile'
            - 'build/*.sh'

  release-gateway-github:
    name: Gateway - GitHub
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.gateway == 'true' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Release
        run: |
          make gateway.release.github GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

  release-gateway-dockerhub:
    name: Gateway - DockerHub
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.gateway == 'true' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: theeadie
          password: ${{ secrets.DockerHubAccessToken }}

      - name: Release
        run: |
          make gateway.release.dockerhub

  release-wa-runner-github:
    name: WA Runner - GitHub
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.wa-runner == 'true' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Release
        run: |
          make wa-runner.release.github GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

  release-wa-runner-dockerhub:
    name: WA Runner - DockerHub
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.wa-runner == 'true' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: theeadie
          password: ${{ secrets.DockerHubAccessToken }}

      - name: Release
        run: |
          make wa-runner.release.dockerhub
